/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pete
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form Screen1
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton29 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblHiddenWord = new javax.swing.JLabel();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        lblTries = new javax.swing.JLabel();

        jButton29.setText("A");

        jButton21.setText("A");

        jButton28.setText("A");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(618, 235, 235, 235));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Welcome to Hangman");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        lblHiddenWord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHiddenWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHiddenWord.setText("X X X X X X X X  X X X X X X X X");
        jPanel1.add(lblHiddenWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        btnA.setText("A");
        btnA.setMaximumSize(new java.awt.Dimension(42, 42));
        btnA.setMinimumSize(new java.awt.Dimension(42, 42));
        btnA.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        btnB.setText("B");
        btnB.setMaximumSize(new java.awt.Dimension(42, 42));
        btnB.setMinimumSize(new java.awt.Dimension(42, 42));
        btnB.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        btnC.setText("C");
        btnC.setMaximumSize(new java.awt.Dimension(42, 42));
        btnC.setMinimumSize(new java.awt.Dimension(42, 42));
        btnC.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        btnD.setText("D");
        btnD.setMaximumSize(new java.awt.Dimension(42, 42));
        btnD.setMinimumSize(new java.awt.Dimension(42, 42));
        btnD.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        btnE.setText("E");
        btnE.setMaximumSize(new java.awt.Dimension(42, 42));
        btnE.setMinimumSize(new java.awt.Dimension(42, 42));
        btnE.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        btnF.setText("F");
        btnF.setMaximumSize(new java.awt.Dimension(42, 42));
        btnF.setMinimumSize(new java.awt.Dimension(42, 42));
        btnF.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        btnG.setText("G");
        btnG.setMaximumSize(new java.awt.Dimension(42, 42));
        btnG.setMinimumSize(new java.awt.Dimension(42, 42));
        btnG.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        btnH.setText("H");
        btnH.setMaximumSize(new java.awt.Dimension(42, 42));
        btnH.setMinimumSize(new java.awt.Dimension(42, 42));
        btnH.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        btnI.setText("I");
        btnI.setMaximumSize(new java.awt.Dimension(42, 42));
        btnI.setMinimumSize(new java.awt.Dimension(42, 42));
        btnI.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnI, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        btnJ.setText("J");
        btnJ.setMaximumSize(new java.awt.Dimension(42, 42));
        btnJ.setMinimumSize(new java.awt.Dimension(42, 42));
        btnJ.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        btnK.setText("K");
        btnK.setMaximumSize(new java.awt.Dimension(42, 42));
        btnK.setMinimumSize(new java.awt.Dimension(42, 42));
        btnK.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        btnL.setText("L");
        btnL.setMaximumSize(new java.awt.Dimension(42, 42));
        btnL.setMinimumSize(new java.awt.Dimension(42, 42));
        btnL.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        btnM.setText("M");
        btnM.setMaximumSize(new java.awt.Dimension(42, 42));
        btnM.setMinimumSize(new java.awt.Dimension(42, 42));
        btnM.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        btnN.setText("N");
        btnN.setMaximumSize(new java.awt.Dimension(42, 42));
        btnN.setMinimumSize(new java.awt.Dimension(42, 42));
        btnN.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        btnO.setText("O");
        btnO.setMaximumSize(new java.awt.Dimension(42, 42));
        btnO.setMinimumSize(new java.awt.Dimension(42, 42));
        btnO.setPreferredSize(new java.awt.Dimension(46, 46));
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });
        jPanel1.add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        btnP.setText("P");
        btnP.setMaximumSize(new java.awt.Dimension(42, 42));
        btnP.setMinimumSize(new java.awt.Dimension(42, 42));
        btnP.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        btnQ.setText("Q");
        btnQ.setMaximumSize(new java.awt.Dimension(42, 42));
        btnQ.setMinimumSize(new java.awt.Dimension(42, 42));
        btnQ.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        btnR.setText("R");
        btnR.setMaximumSize(new java.awt.Dimension(42, 42));
        btnR.setMinimumSize(new java.awt.Dimension(42, 42));
        btnR.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        btnS.setText("S");
        btnS.setMaximumSize(new java.awt.Dimension(42, 42));
        btnS.setMinimumSize(new java.awt.Dimension(42, 42));
        btnS.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        btnT.setText("T");
        btnT.setActionCommand("V");
        btnT.setMaximumSize(new java.awt.Dimension(42, 42));
        btnT.setMinimumSize(new java.awt.Dimension(42, 42));
        btnT.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        btnV.setText("V");
        btnV.setMaximumSize(new java.awt.Dimension(42, 42));
        btnV.setMinimumSize(new java.awt.Dimension(42, 42));
        btnV.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        btnW.setText("W");
        btnW.setMaximumSize(new java.awt.Dimension(42, 42));
        btnW.setMinimumSize(new java.awt.Dimension(42, 42));
        btnW.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnW, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        btnX.setText("X");
        btnX.setMaximumSize(new java.awt.Dimension(42, 42));
        btnX.setMinimumSize(new java.awt.Dimension(42, 42));
        btnX.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        btnY.setText("Y");
        btnY.setMaximumSize(new java.awt.Dimension(42, 42));
        btnY.setMinimumSize(new java.awt.Dimension(42, 42));
        btnY.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        btnZ.setText("Z");
        btnZ.setMaximumSize(new java.awt.Dimension(42, 42));
        btnZ.setMinimumSize(new java.awt.Dimension(42, 42));
        btnZ.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        btnU.setText("U");
        btnU.setMaximumSize(new java.awt.Dimension(42, 42));
        btnU.setMinimumSize(new java.awt.Dimension(42, 42));
        btnU.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanel1.add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        btnStart.setText("Start Game");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        lblTries.setBackground(new java.awt.Color(153, 153, 153));
        lblTries.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTries.setText("0 tries");
        lblTries.setOpaque(true);
        lblTries.setVisible(false);
        jPanel1.add(lblTries, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        
        lblTries.setVisible(true);
        
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHiddenWord;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTries;
    // End of variables declaration//GEN-END:variables
}
